// Regenerates src/Icons.php from lucide-static (the redesign uses lucide-react ^1.26.0).
// Run: docker compose run --rm node node scripts/build-icons.mjs
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const VERSION = '1.26.0';
const NAMES = [
	'arrow-left', 'arrow-right', 'baby', 'building-2', 'calendar-days', 'car', 'chevron-left', 'chevron-right',
	'circle-check', 'clock', 'compass', 'hand-coins', 'headphones', 'heart-handshake', 'house', 'mail', 'map-pin',
	'monitor-play', 'phone', 'play', 'shield-check', 'shirt', 'sparkles', 'users',
];

const dir = mkdtempSync( join( tmpdir(), 'lucide-' ) );
execFileSync( 'npm', [ 'pack', `lucide-static@${ VERSION }`, '--pack-destination', dir ], { stdio: 'inherit' } );
execFileSync( 'tar', [ '-xzf', join( dir, `lucide-static-${ VERSION }.tgz` ), '-C', dir ] );

const rows = NAMES.map( ( name ) => {
	const svg = readFileSync( join( dir, 'package', 'icons', `${ name }.svg` ), 'utf8' );
	const inner = svg.replace( /^[\s\S]*?<svg[^>]*>/, '' ).replace( /<\/svg>\s*$/, '' ).replace( /\s*\n\s*/g, '' ).trim();
	return `\t\t'${ name }' => '${ inner.replace( /\\/g, '\\\\' ).replace( /'/g, "\\'" ) }',`;
} );

copyFileSync( join( dir, 'package', 'LICENSE' ), 'LICENSE-lucide.txt' );
writeFileSync( 'src/Icons.php', `<?php
namespace Elevation\\Core;

/**
 * Allow-listed Lucide icons (lucide-static ${ VERSION }, ISC licence: LICENSE-lucide.txt).
 * Generated by scripts/build-icons.mjs — edit NAMES there and re-run; don't edit this file.
 */
final class Icons {

	public const PATHS = [
${ rows.join( '\n' ) }
	];

	/** Inline SVG for an allow-listed icon, or '' for an unknown name. */
	public static function svg( string $name, string $class = '' ): string {
		if ( ! isset( self::PATHS[ $name ] ) ) {
			return '';
		}
		$class = htmlspecialchars( trim( 'lucide lucide-' . $name . ' ' . $class ), ENT_QUOTES, 'UTF-8' );
		return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="' . $class . '" aria-hidden="true" focusable="false">' . self::PATHS[ $name ] . '</svg>';
	}

	/** @return list<string> */
	public static function names(): array {
		return array_keys( self::PATHS );
	}
}
` );
console.log( `Wrote src/Icons.php (${ NAMES.length } icons, lucide-static ${ VERSION })` );
